### ISSUE TITLE
[Feature Request] Rating and Tagging

### ISSUE THREAD

**Issue by GrimPixel** [tosimplicity/anki-preview-slideshow#3]
I think it could be better to add a function to tag the cards (slides) with “adeptness_bad”, “adeptness_medium” and “adeptness_good” using keys “1”, “2”, “3”, so it would be a fast way to find out what to pay more attention to for a new deck.

**Comment by GrimPixel** [comment]
Somebody created a similar thing https://ankiweb.net/shared/info/1765221856

**Comment by tosimplicity** [comment]
thanks for your comment.
